2024-11-24 17:13:37,196 | tests_12_4.py | "test_challendge" выполнен успешно
2024-11-24 17:13:37,196 | tests_12_4.py | "test_run" выполнен успешно
2024-11-24 17:13:37,197 | tests_12_4.py | Неверный тип данных для объекта Runner
